### PR TITLE
feat: label project paths that do not exist

### PR DESCRIPTION
**Pull request by logan-connolly**
Hi @claidler as we discussed in #37 this is a safer approach to filtering out projects that do not exist on file system.

The last attempt, I tried to modify the underlying file, but that had unintentional consequences. Hopefully this implementation does what it is supposed to do. I tested it with the test case that you described in #37 and it worked fine. 

Please have a look when you have a chance 🙂

### CODE REVIEW

**Comment by claidler** [comment]
This is really nice @logan-connolly and works well. However, I'm concerned that the projects that are no longer valid are remaining in the teslescope-projects.txt file. It's probably not an issue in 99.9% of cases, but seems unnecessary when we could delete these projects from the text file or mark them in the text file, so they show up in the project screen as removed, disable selecting them, and then at least allow people to manually delete them?

**Comment by logan-connolly** [comment]
Hi @claidler yeah I just wanted to push something that I was certain it would work. I really like the idea of marking missing projects that are missing in the project picker (maybe different color? muted grey? or alert red?). That way the user can do as they please by either adding the project to the path or delete via actions. Deleting behind the scenes is a bit sketchy and that was apparent in the last PR which had some unintentional consequences 😅

**Comment by claidler** [comment]
Yeah muted would be good I reckon (red is a bit too in your face) and a `[missing files]` or something like that at the end of the project title. 
I left a comment in the code asking about the is_activated property. It doesn't seem to be being used currently? Maybe we could set that to 0 when the project dir is missing and then change the display based on that?

**Comment by logan-connolly** [comment]
@claidler how does this look?

https://user-images.githubusercontent.com/16244943/122675082-2ba05100-d1d8-11eb-8207-77f7972ae9bd.mp4

**Comment by claidler** [comment]
This looks nice. I think it might be difficult to adjust the colour (at least I wouldn't know how). We could do with not allowing people to select the deleted ones, and showing a user friendly error message.. something I should have considered previously

**Comment by logan-connolly** [comment]
Hi @claidler please have a look. I took your advice and handled the case when the path does not exist. Instead of throwing an error it just prints that the path does not exists and exits telescope picker.

**Review by claidler — COMMENTED** [review]
Thanks 😊 this is great. Makes a lot of sense checking the path rather than the title.. it's been on the back of my mind to update that.

**Comment by logan-connolly** [comment]
Awesome 😊 also I noticed that you added insert key maps, which I think makes it way more intuitive! However, the ctrl-c option kind of threw me off because I used that before to exit the prompt from insert mode, but now it creates a project. How do you exit the prompt in insert mode?

**Comment by claidler** [comment]
Ah okay, good point. I exit the prompt by pressing escape. I'll change that to ctrl+n. Personally I'll always use the normal mode mappings I think, as I tend to think of ctrl+something as an emacs thing (not that I have anything against emacs, but just seems more vim like to do these things in normal mode). Someone asked for those mappings, so I put them in for others.

**Comment by claidler** [comment]
Looking forward there are a couple of things I want to do with this project. It would be good to get your thoughts on these? Not related to this PR, but as we're here.... ! 

1) I noticed that we're no longer deleting projects, just deactivating them. I think we should delete them as we were previously. If the user is selecting to 'delete' a project from the window, then I think we should actually delete the project. I can't see any problem with doing that. It will be much safer now you've done the work to check against paths rather than names. The only advantage 'deactivating' instead would give, is allowing the user to undo, but for something like this - it seems minimal effort just to re-add a project, so not worthwhile. 

2) Potentially allow custom key mappings. I'm not sure how to do this, and am wondering if you have any ideas? I guess we could just pass the key mappings through in the telescope project setup, and then say - if it's set there, then use that custom key mappings, otherwise use the default. It didn't seem like a necessary feature until I added these insert mode key mappings, where there have been a few conflicts, so I think it would be good to take the pressure of the maintainers for this one.

3) Workspaces has been a 'todo' task for a while, as I've been thinking about how to do it. I have an idea for what I think is a pretty good implementation. The user is given 9 possible workspaces, accessed through ctrl+1, ctrl+2 .... ctrl+9. ctrl+0 is the default (contains all projects). We could add a w1, w2..... w9, part to the project lines in the telescope-project txt file. Then we'd just need to manipulate that part of the string to move projects between workspaces. The user can override the default project workspace when telescope-project is opened within the nvim config plugins options. 

I kind of wish I went for json/yml format or something else in hindsight. Seems like more of a long term goal to switch to using something else though.

Points 1 and 2 I think could be tackled short term, and 3 I'll set up another branch to work on at some point soon as it'll be a fair bit of work

**Comment by claidler** [comment]
decided on ctrl+a in the end for adding a new project. I know people have ctrl+n for nerd-tree plugins. These insert mode mappings are going to have a few conflicts for people I think

**Comment by logan-connolly** [comment]
@claidler To your questions above (while we are here :smile:):

1. I think the decision to do it that way stemmed from the recurring insertion of .git projects from setting `base_dir`. So basically, we needed a way to avoid "deleted" projects from being repeatedly added back by the project scanner, which scans every time nvim is launched. I am definitely open to looking into a potential better way of doing this though :+1: 
2. 100% agree with this! Need to look into the underlying telescope code, but I have a hunch that you are right; it could have to  do with the `setup` function. This would greatly lighten the load for you, so I think we should knock this out ASAP. Plus everyone's setup has its tiny differences. Like hitting escape for me while I am in the picker just changes to normal mode; it does not exit the picker.
3. I see a lot of potential in the workspaces idea!! I am not sure that it would be too difficult to implement with the current data structure. We would add another `=` separator and default the workspace value to -1 when projects initialized. Then basically we create an action that expects a 0 >= number < 9 and fetches the path accordingly. Obviously, there is a bit more to it, like preventing duplicate workspace numbers, etc. We should definitely open a ticket for brainstorming ideas on how to implement it :+1: 

I do agree that a different data structure would greatly improve the readability of `telescope-projects.txt`, but I think the challenge would be read/write from lua. Would that entail third party packages or would we have to write the parsing logic ourselves, which could be buggy?

Also, thank you for being so open to collaborate. Like I said in my initial PR, I think this project has incredible potential and it has been really fun working on an open-source project that I use everyday :smile:

**Comment by claidler** [comment]
Thanks @logan-connolly. I genuinely appreciate the help and very much welcome support and collaboration. It is good fun. 

1. Ah I see. Okay that makes more sense! Okay, let's come back to that one. It's not killing anyone.
2. Awesome! Yeah I have to hit escape twice to exit - once to normal mode and then to exit, I hadn't actually considered ctrl+c, but yeah I can see why it would be a pain if you're used to that. That does highlight the problem well. We may be able to grab some code from another plugin doing this, otherwise I can't imagine it'd be too difficult to figure out.
3. Glad you like it! I'm pretty excited about it. I'll get a ticket open. I guess we could default the workspace value for projects to 0, if 0 is for all projects. I'll open a ticket to discuss there.

Oh I see okay, so it's a lua limitation. It was suggested to use a text file, but that makes sense now. I'm not at all familiar with lua before this plugin, it's been a learning experience.

**Pull request merged**
