### PR TITLE
feat: workspaces

### PR DESCRIPTION
**Pull request by matu3ba**
Finished PR for workspaces such that users can see workspaces, while stuff remains working.
What is missing are keybindings and filters, which I want to introduce with 2 other PRs.

Keybindings:
-  are planned to be reduced, so that `c,d,r` get a separate function entry.
- complex editing rules works best with calling the project file itself and stuff like vim-table, so we dont support it (and only give hints how to convert to csv or how to use table plugins for neovim)
- `s,b,w,f` look unintuitive, when they actually mean `:lcd repo, find x` or `:cd repo; find y` or `find y repo` or `launch_poor_file_browser` (the latter without customization is much, much slower than `:cd repo; nnn.nvim`.
- So personally I would remove everything besides `:lcd repo, :cd repo` and require user functions from README to do the setup with the file navigator of choice.

Filters:
- I love zoxide or z, so providing intuitive and filters that can match each column sounds to me the best way
- 1. title, 2. workgroup, 3. path to repo, 4. inactive, 5. bare is the column format and will be possible to filter `t title1 w group1 p path1 i b +` or `b -` where absence of i defaults to active and the rest matches everything unless specified or any other order.
- The plugin thus requires for correct functionality of filters that any name must be two characters. If one uses exact matches, it will work as usual.

Checking for path normalization and clashes is another planned feature, that will implemented eventually (in plenary).

### CODE REVIEW

**Comment by matu3ba** [comment]
@claidler The missing pieces were rather trivial, but I would like to refactor the keybindings as explained here and in #75.

Further I would like to close the answered issues. When do you have time/can take time to review the changes?

**Comment by claidler** [comment]
Looks great @matu3ba  nice work.

**Review by claidler — APPROVED** [review]

**Comment by claidler** [comment]
@matu3ba would you be happy/able to handle the existing and any other PRs coming through for the foreseeable if I gave you access rights?

**Comment by matu3ba** [comment]
@claidler Yes. I might not be able to develop much until end of December, but I can handle issues and PRs.
Do you have any objection on the course I elaborated in #75 ?

**Comment by claidler** [comment]
@Conni2461 do I have the rights on this repo to do this, or is it something you'd have to setup? @matu3ba in regards to issue 75, all sounds good, apart from the point about this - "Move the core logic for managing projects and workspaces outside of telescope", this is something that we have decided against after further consideration.

**Comment by matu3ba** [comment]
> "Move the core logic for managing projects and workspaces outside of telescope", this is something that we have decided against after further consideration.

To me it sounds good to provide "how to lookup git projects" for plugins to provide per-project functionality in ways that can be sandboxed and are uniform

On the flipside, enabling writing of telescope-project.txt from other plugins is a **bad idea** and only providing read-functionality feels very weird to put into std.
This feels like the classic "user must configure this" thing, because the authority of who may edit telescope-project.txt is otherwise unclear.

Unfortunately this cant be solved satisfying within lua due to what plugins have access to and would require to split the plugin into a "read-only"-part for other projects to use. And the "write" part, which includes the "read-only" part plus picker functionality etc.
Plugins could still not make dependencies on the write-parts explicit in the plugin manager, but at least its very clear that they wont interfere with telescope-project. However this would still be annoying.

So after some thought I agree that it is a bad idea, at least in lua. In a language with proper access modifiers (exported and non-exported functions) this would work fine.

**Pull request merged**
