### PR TITLE
Feat/Add Project Scanner 

### PR DESCRIPTION
**Pull request by logan-connolly**
# Motivation

Firstly, I want to say thank you all for adding this awesome extension to telescope! Switching seemlessly through projects has become such a game changer in my development workflow. So I wanted to contribute by tackling the issue of automatically adding  git projects into the `telescope-projects.txt`. However, as I was working through the problem, I began to start refactoring some of the code base. I will attempt to explain the core changes in this PR, but of course comment below if you have an questions or concerns.

# Issues

### Base Directory

Instead of scanning the entire file system, I wanted the user to be able to set a `base_dir` option, from where `.git` directories can be recursively searched.

### Max Depth

I also wanted the user to be able to specify a `max_depth` option as a way of speeding search or avoid nested submodules in repositories.

### Support Telescope Setup

Instead of supplying these options at `project` picker, I wanted to supply them in the telescope setup function call.

Example Setup:

```lua
require('telescope').setup {
  extensions = {
    project = {
      base_dir = '~/projects',
      max_depth = 3
    }
  }
}
```

### Telescope Projects File

In order to continously scan for projects, we need a way of flagging which ones were deleted (or more precisely - deactivated) by the user - or else, the scanner will continuously dump deleted projects back into projects.

I accomplished this by adding a flag to the project line data structure, instantiating the activated flag to 1. I made sure the code is backward-compatible with the legacy data structure `telescope-projects.txt`, by treating a missing activated field as 1.

```shell
# legacy: title=path
telescope-project.nvim=/home/user/projects/telescope.nvim

# new: title=path=activated (activated field can be 1 or 0)
telescope-project.nvim=/home/user/projects/telescope.nvim=1
```

## Project Structure

I quickly realized that the `project.lua` was getting increasingly large, so I had a look at the [telescope.nvim docs](https://github.com/nvim-telescope/telescope.nvim/wiki/Extensions#extension-folder-structure), and adapted the file structure accordingly.

This also forced me to have a look at which functionality we could factor out into own functions. So now the project is structured like so:

```shell
lua
└── telescope
    └── _extensions
        ├── project
        │   ├── actions.lua  # custom telescope actions
        │   ├── finders.lua  # custom telescope finder
        │   ├── git.lua      # git project scanning
        │   ├── main.lua     # main setup of telescope extension
        │   └── utils.lua    # general utilities
        └── project.lua      # register extension
```

## Conclusion

I have tested the changes manually, and everything thing seems to work great. I would be really happy if you could also check it out and give me some feedback. 

I will also look into writing some unittests for the extension as well to make pull requests easier.

# Edits:

- added linting and testing for some modules
- changed when the projects will be scanned (during setup). This has two advantages: 
    1. the  user will see the projects immediately on first call to projects picker (before you needed to close and open again) 
    2. it runs only once per session instead of each time you call the projects pickers, so better performance.

### CODE REVIEW

**Comment by tami5** [comment]
😍 😍 😍 😍 😍 😍 😍 😍 😍 😍 
@logan-connolly, Honestly great work. I will review tom and give some feedback. I've been meaning to integrate the extension to my workflow for the longest time but I guess this is the time to adopt it.

Thanks ❤️

**Comment by claidler** [comment]
This is very cool @logan-connolly thank you! Great work. I'll have a proper look into this later today. I've been thinking about doing a tidy up for a while. It started off okay, but grew into a bigger project so was needing this. Automatically checking for deleted projects is a really good idea also. Much appreciated

**Comment by logan-connolly** [comment]
@claidler thanks for the feedback! Once again, thanks a lot for laying the ground work. 

> It started off okay, but grew into a bigger project so was needing this. 

In the end, it was rather easy to refactor because all of the hard stuff was already done, particularly with the the actions and pickers 😄  Anyway, I am really excited to see where this project goes; I think there is a ton of potential.

**Review by claidler — APPROVED** [review]
Looks great. Thanks again @logan-connolly

**Pull request merged**
