### PR TITLE
Draft: Feat/workspaces

### PR DESCRIPTION
**Pull request by claidler**

### CODE REVIEW

**Comment by mellery451** [comment]
sorry if this is obvious - but are workspaces analogous to vim sessions? I'd love to be able to manage multiple sessions for a given "project" (where project == a repo). Sometimes I want a session that deals with just groups of files related to the build system, or a particular subcomponent and being able to save/reload sessions (aptly-named) for each of these project sub-topics is really useful. This is something that ctrlspace does really well (https://github.com/vim-ctrlspace/vim-ctrlspace/blob/master/doc/ctrlspace.txt#L630) but I'd love to replace that with a telescope enabled option. FWIW, ctrl-space by default just saves session files into the .git subdir...or other repo metadata dirs for other scms.

**Comment by Conni2461** [comment]
@claidler How is it going? Are you still working on this or the Project.

@matu3ba, who opened https://github.com/nvim-telescope/telescope-project.nvim/issues/63 would be interested in picking it up because he needs it for his project (which is based on this project).

**Comment by claidler** [comment]
Hi @Conni2461  personal circumstances have caused me to take a break from this. I'm intending to come back to it, but would appreciate any help, so very happy for someone to take over whilst I'm unavailable. Thanks

**Comment by Conni2461** [comment]
Thats fine. Everybody needs a break from time to time :)

Then if @matu3ba is still interested. I suggest you open a new PR (based on this one) that finishes the implementation. I then can review and merge it :) After that we can talk about having a second maintainer/Collaborator here as a little helper :) because the core telescope team doesnt have the time right now to also maintain extension repos.

**Comment by matu3ba** [comment]
Hey @claidler, author of telescope-project-scripts here. I can finish this feature, but I need some answers regarding usability.

From what I understand of the code is that you made any projects being possible to be bundled inside a workspace and I think that is the easiest approach, which goes the least into the way of people and doesnt try to deal with any dependency or path stuff.
(which is good)

1. How do you intend to filter results by workspace?
2. Do you want to keep track of the current workspace (if project is part of one)? If yes, where?
3. Should the project listing shown via `require'telescope'.extensions.project.project{}` show what projects are part of a workspace? If yes, how?
4. As I understand it, the file representation is fixed, but user interaction is missing. Am I missing relevant context or questions necessary to understand how the feature should work? 

Some other nits are in the issues, but not too relevant to get this finished.

**Comment by claidler** [comment]
Hi @matu3ba thanks for looking into this. I'll try and answer these best I can, although I'd be very happy for you to come up with your own way of doing this, if you'd prefer, as I didn't get too far into it. I do think this implementation would work quite well though.

> 1. How do you intend to filter results by workspace?

You can see every line in the project txt file has a title, path, workspace and activated property, all separated by '='. So an example line (project) in the file would be: `myProjectTitle=/home/claidler/projectFiles=w2=1` 
So that project belongs to `workspace 2`, as it has w2 in it. So to filter all projects to only show workspace 2 projects, for instance, I'd split the string by the '=' sign, and then get the part specific to the workspace, and then say if it's 'w2', show it. 

> 2. Do you want to keep track of the current workspace (if project is part of one)? If yes, where?

 If you mean keep track of the workspaces the user is currently in, then yes. I was thinking wed have to have a separate file, to keep track of that. Currently there is just the projects txt file, but we'd need one for workspaces also

> 3. Should the project listing shown via `require'telescope'.extensions.project.project{}` show what projects are part of a workspace? If yes, how?

That would be nice. As I said in my answer to the first question, the project would have the workspace number assigned to it via the w2 (workspace 2) part, or w3/4/5, etc, in the project file, so you could just use that.

> 4. As I understand it, the file representation is fixed, but user interaction is missing. Am I missing relevant context or questions necessary to understand how the feature should work? 

When telescope project is open, it will default to workspace 0 (unless a different default is set via some global nvim config), this will show 'all projects' projects from workspaces 1-9 and any projects that are yet to be assigned to a workspace. When a user adds a project for the first time, the project will be added to w0 (workspace 0), which is the equivalent of unassigned. When the user opens the telescope project window, they can then assign that project to a different workspace via some key command (e.g. ctrl+w) and then input a number to specify the workspace the project should be assigned to. This change the 'w0' part in the text file to be 'w1' or 'w2' or whatever workspace has been set. Now when the user opens the telescope project window they can then switch between workspaces to see a list of projects in the various workspaces. 


> Some other nits are in the issues, but not too relevant to get this finished.

**Comment by matu3ba** [comment]
@claidler Hey, I fixed the test cases and have the basic design idea done.

I am not satisfied with only providing numbers. From my point of view the interface is faster with single letters for setting any specific filter and making everything else working with the fzf algorithm.

My not fully polished vision of the "ultimate project handler":
Column: 1. user name for repo, 2. path to repo, 3. workgroup, 4. active, 5. path_to_worktree
1. zig=/home/misterspoon/dev/git/zig/zig=0=1=0                               
2. zigbare=/home/misterspoon/dev/git/zig/zig=compiler=1=1
3. zigmaster=/home/misterspoon/dev/git/zig/zig/master=compiler=1=master
Rows:
1. is a normal repo (default)
2. is a bare repo
3. is a worktree with name master

Assumptions for a filter search(1-2), selection of projects(3-4) and general(5-6):
 0. Keybindings and popups with interaction are annoying distractions for something frequently used
 1. Any continuous string containing / is an intended path by user
 2. String starting with `z zig` are intended to be switched to with zoxide and co (but we can show the project preview).
 3. We always do `:lcd` and want the status line to show `clwd`. The `cwd` should be at the top window line and it should be possible to set it to the `clwd`.
 4. n for name, p for path, w for workspace are good and memorable abbreviations and sufficient.
 5. Additional logic depending on telescope-project imitates the folder structure of the associate git project.
 6. Users want de-duplication of repository names and paths, where the first one is only to be provided from a specified root directory to a specified depth.
 
Personally I think 4. is missing a vision for git worktrees/bare repositories, which are not yet good supported in neovim [but in the work](https://github.com/ThePrimeagen/git-worktree.nvim).

Unfortunately they are called `worktree`, which overlaps with `workspace` and both are "in git".

From my point of view there must be a notation for "This user repo with name n on path p is git worktree of bare repo with name n on path p", where path may be abbreviated or not (simplicity).

What are your thoughts on the points 0-6 and in special the unfortunate naming coincedence of "worktree" and "workspace"? How could workspace be renamed?

**Pull request closed without merging**
