### PR TITLE
hotfix: fix property access on already installed plugin with projects

### PR DESCRIPTION
**Pull request by AntoscencoVladimir**

### CODE REVIEW

**Comment by AntoscencoVladimir** [comment]
@claidler Hello, please check it as soon as possible. There is a bug when user already have plugin installed and projects and the upgrade plugin with sort feature

Sorry for that issue didn't spotted it during dev

**Comment by claidler** [comment]
Ah thanks for catching it so quickly

**Comment by AntoscencoVladimir** [comment]
> Ah thanks for catching it so quickly

It will be great if someone else can check it too

Thanks in advance and again sorry for the issue!

**Comment by claidler** [comment]
Yeah I just don't have time at the moment unfortunately. I don't want to let users down by ignoring MR'S but also don't have time to test and not currently using neovim so it's not even on my system. Id love a solution to this. I look over the code and make sure there's nothing glaringly breaking before merging and that's the best I can do. Also not able to deal with very big MR's as they are too risky.

**Comment by AntoscencoVladimir** [comment]
> Yeah I just don't have time at the moment unfortunately. I don't want to let users down by ignoring MR'S but also don't have time to test and not currently using neovim so it's not even on my system. Id love a solution to this. I look over the code and make sure there's nothing glaringly breaking before merging and that's the best I can do. Also not able to deal with very big MR's as they are too risky.

@claidler Ok, clear and thanks. Let me know if I can help in some way please. I like this project but unfortunately I'm not advanced in writing plugins with **lua** so that need more experienced developer to review PR. Anyway next time I will be more careful.

**Pull request merged**
