### PR TITLE
change: core logic in project.nvim

### PR DESCRIPTION
**Pull request by oskarskog**
## What
Moved the core logic such as interacting with the projects file (now json, btw) to here https://github.com/oskarskog/project.nvim and added it as a dependency

## Why
[this](https://github.com/nvim-telescope/telescope-project.nvim/projects/3#card-64485938)

Was thinking that `project.nvim` could provide functionality for other plugins and where possible work for multiple VCS systems.

### CODE REVIEW

**Comment by tami5** [comment]
I'm not sure if @claidler approved this or not, but NOT having the new repo under a @claidler is absurd. I mean I approve the intention, I think it's great idea, but under another owner? it doesn't make any sense! .

@claidler is the father of this initiative of facilitating project management in Neovim and I like this to be known without confusion or misunderstanding. 

Anyways, @oskarskog forgive for being direct, this just my ignorant reaction to what seems to be happening here.

**Comment by oskarskog** [comment]
@tami5 I don't want to take anything away from @claidler, as you say, project management was his initiative. I'm happy to transfer the project to him. The reason for why it's under my account is just that I found myself with some free time and put it together, and then made the effort visible here. 

I sent a transfer request just now, will update the PR later.

**Comment by claidler** [comment]
@Conni2461 how do you feel about this one?

**Comment by Conni2461** [comment]
Its your decision but i think its weird to move the code to any new repository, because its a significant breaking change (especially without any checks if `project.nvim` is even installed :wink:). 

Some thoughts i had, why not experiments here with some of the thoughts you had, build good interfaces and extend them. You could also rename this repository into `project.nvim` and have the telescope part be optional (similar to `octo.nvim`, doesnt really matter if the telescope part can be slimmed down to 100 lines, and if its never loaded.

Moving code, (especially without crediting the original work, `MIT` requires that), does not really acknowledge the work of all contributors who have put work into the project here.

I know this project grow to something different than what @claidler pitched me 7 months ago when "we" started it (i only reviewed the first PR) but i would really think hard about the next steps :)

**Comment by tami5** [comment]
> Its your decision but i think its weird to move the code to any new repository, because its a significant breaking change (especially without any checks if `project.nvim` is even installed 😉).
> 
> Some thoughts i had, why not experiments here with some of the thoughts you had, build good interfaces and extend them. You could also rename this repository into `project.nvim` and have the telescope part be optional (similar to `octo.nvim`, doesnt really matter if the telescope part can be slimmed down to 100 lines, and if its never loaded.
> 
> Moving code, (especially without crediting the original work, `MIT` requires that), does not really acknowledge the work of all contributors who have put work into the project here.
> 
> I know this project grow to something different than what @claidler pitched me 7 months ago when "we" started it (i only reviewed the first PR) but i would really think hard about the next steps :)

Make so much since to me to rename or move ownership than destroying git history. I agree with @Conni2461 at experimenting also. Let's create a new branch and let be project.nvim, it would be fun, and then when it matures and isolates telescope, we can rename it, no need for further setup, works like `octo.nvim`.

**Comment by claidler** [comment]
Thanks @Conni2461. Really good points there. It's something that was considered originally here - https://github.com/nvim-telescope/telescope-project.nvim/issues/49 and I put it in the roadmap under 'draft', as I knew it'd need further thought before implementation, with such a big change. I wouldn't want to upset users, contributors or the team here for sure. 

I don't feel comfortable moving the entire repo to my my personal account. My original thought was to make a separate account like nvim-telescope, but nvim-project or something with a team around it there, including all the people that have contributed so far.

I appreciate that we started this together @Conni2461 - you gave me a lot of help to get started. That's why I asked your thoughts here.

@oskarskog I'm going to have to close this one at this point. I very much appreciate your work on telescope-project and I'm sorry for potentially being misleading. If you start a fresh project management plugin on your personal account to be used by fzf, telescope, etc, I'd be very happy to contribute there. I'll update the heading from draft to 'in consideration' or something similar, and add a 'to do' column to make things clearer. Thanks for your effort.

**Comment by oskarskog** [comment]
@claidler That's alright, generally I'm just happy I found this plugin, it's essential for my workflow. I won't be creating an other project as I, unfortunately, wouldn't have enough time to maintain it. Besides, experimenting like @Conni2461 said is perhaps an even better idea.

**Pull request closed without merging**
