### PR TITLE
feat: handle missing project paths

### PR DESCRIPTION
**Pull request by logan-connolly**
# Motivation

Projects that do not exist anymore on the system should not be displayed in `projects` picker.

# Solution

Add a `cleanup_missing_projects` utility that will run at setup (each time neovim session is started) which will remove projects from `telescope-projects.txt` where the file path does not exist in file system. Also during a given session, filter out projects whose paths' do not exist.

### CODE REVIEW

**Review by claidler — APPROVED** [review]

**Comment by claidler** [comment]
Thanks @logan-connolly

**Comment by claidler** [comment]
@logan-connolly I had to revert this pretty quickly as it deleted all my existing projects in telescope-projects.txt

**Comment by claidler** [comment]
Really appreciate the effort, but we may need to take another look at this one.

**Comment by logan-connolly** [comment]
Hey @claidler, good catch! Thanks for the feedback. That was definitely not the intention 😅

I will have a close look. Sorry about that.

**Comment by claidler** [comment]
Thanks @logan-connolly not sure if it's just me, with my setup. But double checked and got the same result. Let me know if you're unable to replicate and I'll see if I can figure it out

**Comment by logan-connolly** [comment]
Unfortunately, I am unable to reproduce the bug. I just did the following steps:

1. Clean install Plugin from the branch
2. Remove `telescope-projects.txt`
3. Start nvim and checked that git projects were added to `telescope-projects.txt`
4. Added a dummy project `git init --quiet  ~/projects/test`
5. Checked that `test` project shows up in projects picker
6. Exit out of nvim and remove the `test` project from shell
7. Open nvim again and check that `test` project was removed from picker and `telescope-projects.txt`

It all seems to work on linux. It could be an environment issue where the plenary path functionality is not working correctly? I am really not sure.

**Comment by claidler** [comment]
https://user-images.githubusercontent.com/43636691/122116820-fd102800-ce1d-11eb-8b82-d9f470052fa5.mp4

**Comment by claidler** [comment]
I have vim plenary up-to-date, on fedora 34, using suckless terminal

**Comment by claidler** [comment]
I'm trying to figure it out

**Comment by logan-connolly** [comment]
Hey @claidler thanks a lot for all your effort here. There clearly is something up here. I will also continue looking into it.

**Comment by claidler** [comment]
@logan-connolly great! I couldn't figure out the issue

**Comment by logan-connolly** [comment]
Hey @claidler  couldn't quite debug the cleaning up of the `telescope-projects.txt` file. It is not actually necessary though; I just thought it would be good to keep the file clean. 

We could just filter out projects whose path's don't exist anymore when calling the picker? What do you think about that? I just added a fork on my branch and tested your test case from the video and everything worked as expected. Shall I open a new PR for you to test on your machine?

**Comment by claidler** [comment]
@logan-connolly I wonder if it would be better for us to mark them somehow as missing? That way the user can manually delete them from the text file if required. That way the data's not just hanging around. Yes please set up a PR when you can. I unfortunately wont be able to test anything until the weekend but will get to it as soon as I can. Thanks again for all your work here

**Pull request merged**
