### PR TITLE
Allow multiple base dirs in config

### PR DESCRIPTION
**Pull request by oskarskog**
Allows multiple base directory configuration in the setup table, each with it's own max depth.

### CODE REVIEW

**Comment by oskarskog** [comment]
This will break users' current configs, unsure how I feel about that.

**Comment by claidler** [comment]
This is very cool @oskarskog and I'm thinking it may be worth breaking configs for it. It wouldn't take long for people to update. I guess we could do a check on startup like what the telescope guys do, to error if base_dir is used instead of base_dirs. Do you have any suggestions, or happy to go with that?

**Comment by oskarskog** [comment]
@claidler sounds good to me, I'll add the check!

**Comment by claidler** [comment]
> @claidler sounds good to me, I'll add the check!

Really appreciate that thank you!

**Comment by oskarskog** [comment]
@claidler  While I was at it I replaced the `find` call that was causing problems with `plenary.scandir`, I think it's better that way.

**Comment by claidler** [comment]
Amazing! Thanks for your help here @oskarskog. Looking now

**Comment by claidler** [comment]
Works great! Merging now. :-)

**Pull request merged**
