### PR TITLE
fix: file_browser

### PR DESCRIPTION
**Pull request by ikerurda**

### CODE REVIEW

**Review by tami5 — APPROVED** [review]
LGTM

**Comment by matu3ba** [comment]
1. How is this a fix and not a feature?
2. A file browser might be nice to have, but is not essential. Think of file editing via `nnn` or the other file browser plugins.
Or using the terminal.

**Comment by ikerurda** [comment]
I considered this a fix because the builtin `file-browser` picker was moved on [Jan 11](https://github.com/nvim-telescope/telescope.nvim/commit/015a35626d5a293dc9c19dc2bb301f25850961f6) to it's own [extension](https://github.com/nvim-telescope/telescope-file-browser.nvim) but this change never got reflected in  `telescope-project.nvim` and therefore, since then, this functionality has been broken.

**Comment by claidler** [comment]
@ikerurda thanks for this

**Pull request merged**
